# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter_service/filter_web_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='filter_service/filter_web_api.proto',
  package='filter_manager',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#filter_service/filter_web_api.proto\x12\x0e\x66ilter_manager\"R\n\x08Keywords\x12\x14\n\x0c\x61ny_keywords\x18\x01 \x03(\t\x12\x14\n\x0c\x61ll_keywords\x18\x02 \x03(\t\x12\x1a\n\x12\x65xclusion_keywords\x18\x03 \x03(\t\"\x19\n\x17\x46ilterServerInfoRequest\"b\n\x18\x46ilterServerInfoResponse\x12\x12\n\nserver_url\x18\x01 \x01(\t\x12\x13\n\x0bserver_port\x18\x02 \x01(\r\x12\x1d\n\x15server_uptime_seconds\x18\x03 \x01(\x04\"\x14\n\x12GetKeywordsRequest\"C\n\x15UpdateKeywordsRequest\x12*\n\x08keywords\x18\x01 \x01(\x0b\x32\x18.filter_manager.Keywords\"l\n\x12SetKeywordsRequest\x12*\n\x08keywords\x18\x01 \x01(\x0b\x32\x18.filter_manager.Keywords\x12\x19\n\x0cregex_string\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_regex_string\"m\n\x15\x44\x65leteKeywordsRequest\x12*\n\x08keywords\x18\x01 \x01(\x0b\x32\x18.filter_manager.Keywords\x12\x18\n\x0b\x63lear_regex\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\x0e\n\x0c_clear_regex\"T\n\x10KeywordsResponse\x12*\n\x08keywords\x18\x01 \x01(\x0b\x32\x18.filter_manager.Keywords\x12\x14\n\x0cregex_string\x18\x02 \x01(\t2\xde\x03\n\x11TextFilterManager\x12U\n\x0bGetKeywords\x12\".filter_manager.GetKeywordsRequest\x1a .filter_manager.KeywordsResponse\"\x00\x12U\n\x0bSetKeywords\x12\".filter_manager.SetKeywordsRequest\x1a .filter_manager.KeywordsResponse\"\x00\x12[\n\x0eUpdateKeywords\x12%.filter_manager.UpdateKeywordsRequest\x1a .filter_manager.KeywordsResponse\"\x00\x12[\n\x0e\x44\x65leteKeywords\x12%.filter_manager.DeleteKeywordsRequest\x1a .filter_manager.KeywordsResponse\"\x00\x12\x61\n\nServerInfo\x12\'.filter_manager.FilterServerInfoRequest\x1a(.filter_manager.FilterServerInfoResponse\"\x00\x62\x06proto3'
)




_KEYWORDS = _descriptor.Descriptor(
  name='Keywords',
  full_name='filter_manager.Keywords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='any_keywords', full_name='filter_manager.Keywords.any_keywords', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='all_keywords', full_name='filter_manager.Keywords.all_keywords', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exclusion_keywords', full_name='filter_manager.Keywords.exclusion_keywords', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=137,
)


_FILTERSERVERINFOREQUEST = _descriptor.Descriptor(
  name='FilterServerInfoRequest',
  full_name='filter_manager.FilterServerInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=164,
)


_FILTERSERVERINFORESPONSE = _descriptor.Descriptor(
  name='FilterServerInfoResponse',
  full_name='filter_manager.FilterServerInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_url', full_name='filter_manager.FilterServerInfoResponse.server_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_port', full_name='filter_manager.FilterServerInfoResponse.server_port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_uptime_seconds', full_name='filter_manager.FilterServerInfoResponse.server_uptime_seconds', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=264,
)


_GETKEYWORDSREQUEST = _descriptor.Descriptor(
  name='GetKeywordsRequest',
  full_name='filter_manager.GetKeywordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=286,
)


_UPDATEKEYWORDSREQUEST = _descriptor.Descriptor(
  name='UpdateKeywordsRequest',
  full_name='filter_manager.UpdateKeywordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='filter_manager.UpdateKeywordsRequest.keywords', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=355,
)


_SETKEYWORDSREQUEST = _descriptor.Descriptor(
  name='SetKeywordsRequest',
  full_name='filter_manager.SetKeywordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='filter_manager.SetKeywordsRequest.keywords', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regex_string', full_name='filter_manager.SetKeywordsRequest.regex_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_regex_string', full_name='filter_manager.SetKeywordsRequest._regex_string',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=357,
  serialized_end=465,
)


_DELETEKEYWORDSREQUEST = _descriptor.Descriptor(
  name='DeleteKeywordsRequest',
  full_name='filter_manager.DeleteKeywordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='filter_manager.DeleteKeywordsRequest.keywords', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clear_regex', full_name='filter_manager.DeleteKeywordsRequest.clear_regex', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_clear_regex', full_name='filter_manager.DeleteKeywordsRequest._clear_regex',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=467,
  serialized_end=576,
)


_KEYWORDSRESPONSE = _descriptor.Descriptor(
  name='KeywordsResponse',
  full_name='filter_manager.KeywordsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='filter_manager.KeywordsResponse.keywords', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regex_string', full_name='filter_manager.KeywordsResponse.regex_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=578,
  serialized_end=662,
)

_UPDATEKEYWORDSREQUEST.fields_by_name['keywords'].message_type = _KEYWORDS
_SETKEYWORDSREQUEST.fields_by_name['keywords'].message_type = _KEYWORDS
_SETKEYWORDSREQUEST.oneofs_by_name['_regex_string'].fields.append(
  _SETKEYWORDSREQUEST.fields_by_name['regex_string'])
_SETKEYWORDSREQUEST.fields_by_name['regex_string'].containing_oneof = _SETKEYWORDSREQUEST.oneofs_by_name['_regex_string']
_DELETEKEYWORDSREQUEST.fields_by_name['keywords'].message_type = _KEYWORDS
_DELETEKEYWORDSREQUEST.oneofs_by_name['_clear_regex'].fields.append(
  _DELETEKEYWORDSREQUEST.fields_by_name['clear_regex'])
_DELETEKEYWORDSREQUEST.fields_by_name['clear_regex'].containing_oneof = _DELETEKEYWORDSREQUEST.oneofs_by_name['_clear_regex']
_KEYWORDSRESPONSE.fields_by_name['keywords'].message_type = _KEYWORDS
DESCRIPTOR.message_types_by_name['Keywords'] = _KEYWORDS
DESCRIPTOR.message_types_by_name['FilterServerInfoRequest'] = _FILTERSERVERINFOREQUEST
DESCRIPTOR.message_types_by_name['FilterServerInfoResponse'] = _FILTERSERVERINFORESPONSE
DESCRIPTOR.message_types_by_name['GetKeywordsRequest'] = _GETKEYWORDSREQUEST
DESCRIPTOR.message_types_by_name['UpdateKeywordsRequest'] = _UPDATEKEYWORDSREQUEST
DESCRIPTOR.message_types_by_name['SetKeywordsRequest'] = _SETKEYWORDSREQUEST
DESCRIPTOR.message_types_by_name['DeleteKeywordsRequest'] = _DELETEKEYWORDSREQUEST
DESCRIPTOR.message_types_by_name['KeywordsResponse'] = _KEYWORDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Keywords = _reflection.GeneratedProtocolMessageType('Keywords', (_message.Message,), {
  'DESCRIPTOR' : _KEYWORDS,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.Keywords)
  })
_sym_db.RegisterMessage(Keywords)

FilterServerInfoRequest = _reflection.GeneratedProtocolMessageType('FilterServerInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILTERSERVERINFOREQUEST,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.FilterServerInfoRequest)
  })
_sym_db.RegisterMessage(FilterServerInfoRequest)

FilterServerInfoResponse = _reflection.GeneratedProtocolMessageType('FilterServerInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILTERSERVERINFORESPONSE,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.FilterServerInfoResponse)
  })
_sym_db.RegisterMessage(FilterServerInfoResponse)

GetKeywordsRequest = _reflection.GeneratedProtocolMessageType('GetKeywordsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETKEYWORDSREQUEST,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.GetKeywordsRequest)
  })
_sym_db.RegisterMessage(GetKeywordsRequest)

UpdateKeywordsRequest = _reflection.GeneratedProtocolMessageType('UpdateKeywordsRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEKEYWORDSREQUEST,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.UpdateKeywordsRequest)
  })
_sym_db.RegisterMessage(UpdateKeywordsRequest)

SetKeywordsRequest = _reflection.GeneratedProtocolMessageType('SetKeywordsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETKEYWORDSREQUEST,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.SetKeywordsRequest)
  })
_sym_db.RegisterMessage(SetKeywordsRequest)

DeleteKeywordsRequest = _reflection.GeneratedProtocolMessageType('DeleteKeywordsRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEKEYWORDSREQUEST,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.DeleteKeywordsRequest)
  })
_sym_db.RegisterMessage(DeleteKeywordsRequest)

KeywordsResponse = _reflection.GeneratedProtocolMessageType('KeywordsResponse', (_message.Message,), {
  'DESCRIPTOR' : _KEYWORDSRESPONSE,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.KeywordsResponse)
  })
_sym_db.RegisterMessage(KeywordsResponse)



_TEXTFILTERMANAGER = _descriptor.ServiceDescriptor(
  name='TextFilterManager',
  full_name='filter_manager.TextFilterManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=665,
  serialized_end=1143,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetKeywords',
    full_name='filter_manager.TextFilterManager.GetKeywords',
    index=0,
    containing_service=None,
    input_type=_GETKEYWORDSREQUEST,
    output_type=_KEYWORDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetKeywords',
    full_name='filter_manager.TextFilterManager.SetKeywords',
    index=1,
    containing_service=None,
    input_type=_SETKEYWORDSREQUEST,
    output_type=_KEYWORDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateKeywords',
    full_name='filter_manager.TextFilterManager.UpdateKeywords',
    index=2,
    containing_service=None,
    input_type=_UPDATEKEYWORDSREQUEST,
    output_type=_KEYWORDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteKeywords',
    full_name='filter_manager.TextFilterManager.DeleteKeywords',
    index=3,
    containing_service=None,
    input_type=_DELETEKEYWORDSREQUEST,
    output_type=_KEYWORDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ServerInfo',
    full_name='filter_manager.TextFilterManager.ServerInfo',
    index=4,
    containing_service=None,
    input_type=_FILTERSERVERINFOREQUEST,
    output_type=_FILTERSERVERINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEXTFILTERMANAGER)

DESCRIPTOR.services_by_name['TextFilterManager'] = _TEXTFILTERMANAGER

# @@protoc_insertion_point(module_scope)
