# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter_service/filter_web_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='filter_service/filter_web_api.proto',
  package='filter_manager',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#filter_service/filter_web_api.proto\x12\x0e\x66ilter_manager\"R\n\x08Keywords\x12\x14\n\x0c\x61ny_keywords\x18\x01 \x03(\t\x12\x14\n\x0c\x61ll_keywords\x18\x02 \x03(\t\x12\x1a\n\x12\x65xclusion_keywords\x18\x03 \x03(\t\"\x14\n\x12GetKeywordsRequest\"W\n\x13GetKeywordsResponse\x12*\n\x08keywords\x18\x01 \x01(\x0b\x32\x18.filter_manager.Keywords\x12\x14\n\x0cregex_string\x18\x04 \x01(\t\"C\n\x15UpdateKeywordsRequest\x12*\n\x08keywords\x18\x01 \x01(\x0b\x32\x18.filter_manager.Keywords\"D\n\x16UpdateKeywordsResponse\x12*\n\x08keywords\x18\x01 \x01(\x0b\x32\x18.filter_manager.Keywords\"l\n\x12SetKeywordsRequest\x12*\n\x08keywords\x18\x01 \x01(\x0b\x32\x18.filter_manager.Keywords\x12\x19\n\x0cregex_string\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_regex_string\"W\n\x13SetKeywordsResponse\x12*\n\x08keywords\x18\x01 \x01(\x0b\x32\x18.filter_manager.Keywords\x12\x14\n\x0cregex_string\x18\x04 \x01(\t\"m\n\x15\x44\x65leteKeywordsRequest\x12*\n\x08keywords\x18\x01 \x01(\x0b\x32\x18.filter_manager.Keywords\x12\x18\n\x0b\x63lear_regex\x18\x04 \x01(\x08H\x00\x88\x01\x01\x42\x0e\n\x0c_clear_regex\"Z\n\x16\x44\x65leteKeywordsResponse\x12*\n\x08keywords\x18\x01 \x01(\x0b\x32\x18.filter_manager.Keywords\x12\x14\n\x0cregex_string\x18\x04 \x01(\t2\x8d\x03\n\x11TextFilterManager\x12X\n\x0bGetKeywords\x12\".filter_manager.GetKeywordsRequest\x1a#.filter_manager.GetKeywordsResponse\"\x00\x12X\n\x0bSetKeywords\x12\".filter_manager.SetKeywordsRequest\x1a#.filter_manager.SetKeywordsResponse\"\x00\x12\x61\n\x0eUpdateKeywords\x12%.filter_manager.UpdateKeywordsRequest\x1a&.filter_manager.UpdateKeywordsResponse\"\x00\x12\x61\n\x0e\x44\x65leteKeywords\x12%.filter_manager.DeleteKeywordsRequest\x1a&.filter_manager.DeleteKeywordsResponse\"\x00\x62\x06proto3'
)




_KEYWORDS = _descriptor.Descriptor(
  name='Keywords',
  full_name='filter_manager.Keywords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='any_keywords', full_name='filter_manager.Keywords.any_keywords', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='all_keywords', full_name='filter_manager.Keywords.all_keywords', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exclusion_keywords', full_name='filter_manager.Keywords.exclusion_keywords', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=137,
)


_GETKEYWORDSREQUEST = _descriptor.Descriptor(
  name='GetKeywordsRequest',
  full_name='filter_manager.GetKeywordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=159,
)


_GETKEYWORDSRESPONSE = _descriptor.Descriptor(
  name='GetKeywordsResponse',
  full_name='filter_manager.GetKeywordsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='filter_manager.GetKeywordsResponse.keywords', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regex_string', full_name='filter_manager.GetKeywordsResponse.regex_string', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=248,
)


_UPDATEKEYWORDSREQUEST = _descriptor.Descriptor(
  name='UpdateKeywordsRequest',
  full_name='filter_manager.UpdateKeywordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='filter_manager.UpdateKeywordsRequest.keywords', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=317,
)


_UPDATEKEYWORDSRESPONSE = _descriptor.Descriptor(
  name='UpdateKeywordsResponse',
  full_name='filter_manager.UpdateKeywordsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='filter_manager.UpdateKeywordsResponse.keywords', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=387,
)


_SETKEYWORDSREQUEST = _descriptor.Descriptor(
  name='SetKeywordsRequest',
  full_name='filter_manager.SetKeywordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='filter_manager.SetKeywordsRequest.keywords', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regex_string', full_name='filter_manager.SetKeywordsRequest.regex_string', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_regex_string', full_name='filter_manager.SetKeywordsRequest._regex_string',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=389,
  serialized_end=497,
)


_SETKEYWORDSRESPONSE = _descriptor.Descriptor(
  name='SetKeywordsResponse',
  full_name='filter_manager.SetKeywordsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='filter_manager.SetKeywordsResponse.keywords', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regex_string', full_name='filter_manager.SetKeywordsResponse.regex_string', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=586,
)


_DELETEKEYWORDSREQUEST = _descriptor.Descriptor(
  name='DeleteKeywordsRequest',
  full_name='filter_manager.DeleteKeywordsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='filter_manager.DeleteKeywordsRequest.keywords', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clear_regex', full_name='filter_manager.DeleteKeywordsRequest.clear_regex', index=1,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_clear_regex', full_name='filter_manager.DeleteKeywordsRequest._clear_regex',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=588,
  serialized_end=697,
)


_DELETEKEYWORDSRESPONSE = _descriptor.Descriptor(
  name='DeleteKeywordsResponse',
  full_name='filter_manager.DeleteKeywordsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keywords', full_name='filter_manager.DeleteKeywordsResponse.keywords', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regex_string', full_name='filter_manager.DeleteKeywordsResponse.regex_string', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=699,
  serialized_end=789,
)

_GETKEYWORDSRESPONSE.fields_by_name['keywords'].message_type = _KEYWORDS
_UPDATEKEYWORDSREQUEST.fields_by_name['keywords'].message_type = _KEYWORDS
_UPDATEKEYWORDSRESPONSE.fields_by_name['keywords'].message_type = _KEYWORDS
_SETKEYWORDSREQUEST.fields_by_name['keywords'].message_type = _KEYWORDS
_SETKEYWORDSREQUEST.oneofs_by_name['_regex_string'].fields.append(
  _SETKEYWORDSREQUEST.fields_by_name['regex_string'])
_SETKEYWORDSREQUEST.fields_by_name['regex_string'].containing_oneof = _SETKEYWORDSREQUEST.oneofs_by_name['_regex_string']
_SETKEYWORDSRESPONSE.fields_by_name['keywords'].message_type = _KEYWORDS
_DELETEKEYWORDSREQUEST.fields_by_name['keywords'].message_type = _KEYWORDS
_DELETEKEYWORDSREQUEST.oneofs_by_name['_clear_regex'].fields.append(
  _DELETEKEYWORDSREQUEST.fields_by_name['clear_regex'])
_DELETEKEYWORDSREQUEST.fields_by_name['clear_regex'].containing_oneof = _DELETEKEYWORDSREQUEST.oneofs_by_name['_clear_regex']
_DELETEKEYWORDSRESPONSE.fields_by_name['keywords'].message_type = _KEYWORDS
DESCRIPTOR.message_types_by_name['Keywords'] = _KEYWORDS
DESCRIPTOR.message_types_by_name['GetKeywordsRequest'] = _GETKEYWORDSREQUEST
DESCRIPTOR.message_types_by_name['GetKeywordsResponse'] = _GETKEYWORDSRESPONSE
DESCRIPTOR.message_types_by_name['UpdateKeywordsRequest'] = _UPDATEKEYWORDSREQUEST
DESCRIPTOR.message_types_by_name['UpdateKeywordsResponse'] = _UPDATEKEYWORDSRESPONSE
DESCRIPTOR.message_types_by_name['SetKeywordsRequest'] = _SETKEYWORDSREQUEST
DESCRIPTOR.message_types_by_name['SetKeywordsResponse'] = _SETKEYWORDSRESPONSE
DESCRIPTOR.message_types_by_name['DeleteKeywordsRequest'] = _DELETEKEYWORDSREQUEST
DESCRIPTOR.message_types_by_name['DeleteKeywordsResponse'] = _DELETEKEYWORDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Keywords = _reflection.GeneratedProtocolMessageType('Keywords', (_message.Message,), {
  'DESCRIPTOR' : _KEYWORDS,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.Keywords)
  })
_sym_db.RegisterMessage(Keywords)

GetKeywordsRequest = _reflection.GeneratedProtocolMessageType('GetKeywordsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETKEYWORDSREQUEST,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.GetKeywordsRequest)
  })
_sym_db.RegisterMessage(GetKeywordsRequest)

GetKeywordsResponse = _reflection.GeneratedProtocolMessageType('GetKeywordsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETKEYWORDSRESPONSE,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.GetKeywordsResponse)
  })
_sym_db.RegisterMessage(GetKeywordsResponse)

UpdateKeywordsRequest = _reflection.GeneratedProtocolMessageType('UpdateKeywordsRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEKEYWORDSREQUEST,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.UpdateKeywordsRequest)
  })
_sym_db.RegisterMessage(UpdateKeywordsRequest)

UpdateKeywordsResponse = _reflection.GeneratedProtocolMessageType('UpdateKeywordsResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEKEYWORDSRESPONSE,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.UpdateKeywordsResponse)
  })
_sym_db.RegisterMessage(UpdateKeywordsResponse)

SetKeywordsRequest = _reflection.GeneratedProtocolMessageType('SetKeywordsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETKEYWORDSREQUEST,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.SetKeywordsRequest)
  })
_sym_db.RegisterMessage(SetKeywordsRequest)

SetKeywordsResponse = _reflection.GeneratedProtocolMessageType('SetKeywordsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETKEYWORDSRESPONSE,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.SetKeywordsResponse)
  })
_sym_db.RegisterMessage(SetKeywordsResponse)

DeleteKeywordsRequest = _reflection.GeneratedProtocolMessageType('DeleteKeywordsRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEKEYWORDSREQUEST,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.DeleteKeywordsRequest)
  })
_sym_db.RegisterMessage(DeleteKeywordsRequest)

DeleteKeywordsResponse = _reflection.GeneratedProtocolMessageType('DeleteKeywordsResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEKEYWORDSRESPONSE,
  '__module__' : 'filter_service.filter_web_api_pb2'
  # @@protoc_insertion_point(class_scope:filter_manager.DeleteKeywordsResponse)
  })
_sym_db.RegisterMessage(DeleteKeywordsResponse)



_TEXTFILTERMANAGER = _descriptor.ServiceDescriptor(
  name='TextFilterManager',
  full_name='filter_manager.TextFilterManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=792,
  serialized_end=1189,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetKeywords',
    full_name='filter_manager.TextFilterManager.GetKeywords',
    index=0,
    containing_service=None,
    input_type=_GETKEYWORDSREQUEST,
    output_type=_GETKEYWORDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetKeywords',
    full_name='filter_manager.TextFilterManager.SetKeywords',
    index=1,
    containing_service=None,
    input_type=_SETKEYWORDSREQUEST,
    output_type=_SETKEYWORDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateKeywords',
    full_name='filter_manager.TextFilterManager.UpdateKeywords',
    index=2,
    containing_service=None,
    input_type=_UPDATEKEYWORDSREQUEST,
    output_type=_UPDATEKEYWORDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteKeywords',
    full_name='filter_manager.TextFilterManager.DeleteKeywords',
    index=3,
    containing_service=None,
    input_type=_DELETEKEYWORDSREQUEST,
    output_type=_DELETEKEYWORDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEXTFILTERMANAGER)

DESCRIPTOR.services_by_name['TextFilterManager'] = _TEXTFILTERMANAGER

# @@protoc_insertion_point(module_scope)
