# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter_service/text_filter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='filter_service/text_filter.proto',
  package='filter_transport',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n filter_service/text_filter.proto\x12\x10\x66ilter_transport\"/\n\x17SingleTextFilterRequest\x12\x14\n\x0cinput_string\x18\x01 \x01(\t\"1\n\x18SingleTextFilterResponse\x12\x15\n\rpassed_filter\x18\x01 \x01(\x08\",\n\x13MultiFilterResponse\x12\x15\n\rpassed_inputs\x18\x01 \x03(\t2\xd3\x02\n\x11TextFilterService\x12g\n\x0cSingleFilter\x12).filter_transport.SingleTextFilterRequest\x1a*.filter_transport.SingleTextFilterResponse\"\x00\x12\x63\n\x0bMultiFilter\x12).filter_transport.SingleTextFilterRequest\x1a%.filter_transport.MultiFilterResponse\"\x00(\x01\x12p\n\x11MultiFilterStream\x12).filter_transport.SingleTextFilterRequest\x1a*.filter_transport.SingleTextFilterResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)




_SINGLETEXTFILTERREQUEST = _descriptor.Descriptor(
  name='SingleTextFilterRequest',
  full_name='filter_transport.SingleTextFilterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_string', full_name='filter_transport.SingleTextFilterRequest.input_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=101,
)


_SINGLETEXTFILTERRESPONSE = _descriptor.Descriptor(
  name='SingleTextFilterResponse',
  full_name='filter_transport.SingleTextFilterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='passed_filter', full_name='filter_transport.SingleTextFilterResponse.passed_filter', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=152,
)


_MULTIFILTERRESPONSE = _descriptor.Descriptor(
  name='MultiFilterResponse',
  full_name='filter_transport.MultiFilterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='passed_inputs', full_name='filter_transport.MultiFilterResponse.passed_inputs', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=198,
)

DESCRIPTOR.message_types_by_name['SingleTextFilterRequest'] = _SINGLETEXTFILTERREQUEST
DESCRIPTOR.message_types_by_name['SingleTextFilterResponse'] = _SINGLETEXTFILTERRESPONSE
DESCRIPTOR.message_types_by_name['MultiFilterResponse'] = _MULTIFILTERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SingleTextFilterRequest = _reflection.GeneratedProtocolMessageType('SingleTextFilterRequest', (_message.Message,), {
  'DESCRIPTOR' : _SINGLETEXTFILTERREQUEST,
  '__module__' : 'filter_service.text_filter_pb2'
  # @@protoc_insertion_point(class_scope:filter_transport.SingleTextFilterRequest)
  })
_sym_db.RegisterMessage(SingleTextFilterRequest)

SingleTextFilterResponse = _reflection.GeneratedProtocolMessageType('SingleTextFilterResponse', (_message.Message,), {
  'DESCRIPTOR' : _SINGLETEXTFILTERRESPONSE,
  '__module__' : 'filter_service.text_filter_pb2'
  # @@protoc_insertion_point(class_scope:filter_transport.SingleTextFilterResponse)
  })
_sym_db.RegisterMessage(SingleTextFilterResponse)

MultiFilterResponse = _reflection.GeneratedProtocolMessageType('MultiFilterResponse', (_message.Message,), {
  'DESCRIPTOR' : _MULTIFILTERRESPONSE,
  '__module__' : 'filter_service.text_filter_pb2'
  # @@protoc_insertion_point(class_scope:filter_transport.MultiFilterResponse)
  })
_sym_db.RegisterMessage(MultiFilterResponse)



_TEXTFILTERSERVICE = _descriptor.ServiceDescriptor(
  name='TextFilterService',
  full_name='filter_transport.TextFilterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=201,
  serialized_end=540,
  methods=[
  _descriptor.MethodDescriptor(
    name='SingleFilter',
    full_name='filter_transport.TextFilterService.SingleFilter',
    index=0,
    containing_service=None,
    input_type=_SINGLETEXTFILTERREQUEST,
    output_type=_SINGLETEXTFILTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MultiFilter',
    full_name='filter_transport.TextFilterService.MultiFilter',
    index=1,
    containing_service=None,
    input_type=_SINGLETEXTFILTERREQUEST,
    output_type=_MULTIFILTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MultiFilterStream',
    full_name='filter_transport.TextFilterService.MultiFilterStream',
    index=2,
    containing_service=None,
    input_type=_SINGLETEXTFILTERREQUEST,
    output_type=_SINGLETEXTFILTERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEXTFILTERSERVICE)

DESCRIPTOR.services_by_name['TextFilterService'] = _TEXTFILTERSERVICE

# @@protoc_insertion_point(module_scope)
